name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: functions   # Specify the path to checkout

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd functions   # Change directory to functions
          docker build -t anand382/tasty-bites-01:latest .
          docker push anand382/tasty-bites-01:latest
          
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull anand382/tasty-bites-01:latest
      - name: Delete old container
        run: docker rm -f anand382/tasty-bites-01:latest
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name web-server-1 anand382/tasty-bites-01:latest